# You can change this to a different version of Wordpress available at
# https://hub.docker.com/_/wordpress
# https://community.render.com/t/docker-deployment-is-stuck/7858
FROM wordpress:6.2-php8.2-apache

COPY config/php.ini $PHP_INI_DIR/conf.d/php.ini

RUN cp /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/
RUN usermod -s /bin/bash www-data
RUN chown www-data:www-data /var/www
USER www-data:www-data