# You can change this to a different version of Wordpress available at
# https://hub.docker.com/_/wordpress
# https://community.render.com/t/docker-deployment-is-stuck/7858
FROM wordpress:5.0.0-php7.2-apache

COPY config/php.ini $PHP_INI_DIR/conf.d/php.ini
# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/conf.d/php.ini"

RUN usermod -s /bin/bash www-data
RUN chown www-data:www-data /var/www
USER www-data:www-data