services:

- type: pserv
  name: mysql
  env: docker
  dockerfilePath: ./Dockerfile-mysql
  plan: standard
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 20
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true

- type: web
  name: wp-latest-publisher
  env: docker
  dockerfilePath: ./Dockerfile-latest
  plan: starter
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  domains:
    - wordpress.kutoku-publisher.com
  envVars:
  - key: PORT
    value: 80
  - key: WORDPRESS_TABLE_PREFIX
    value: wp_latest_publisher_
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD

- type: web
  name: wp-5-merchant
  env: docker
  dockerfilePath: ./Dockerfile-5
  plan: starter
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  domains:
    - wp5.kutoku-merchant.com
  envVars:
  - key: PORT
    value: 80
  - key: WORDPRESS_TABLE_PREFIX
    value: wp_5_merchant_
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD

- type: web
  name: wp-6-merchant
  env: docker
  dockerfilePath: ./Dockerfile-6
  plan: starter
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  domains:
    - wp6.kutoku-merchant.com
  envVars:
  - key: PORT
    value: 80
  - key: WORDPRESS_TABLE_PREFIX
    value: wp_6_merchant_
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
