services:
- type: web
  name: wordpress
  env: docker
  dockerfilePath: ./version-6-1/Dockerfile
  plan: starter
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  domains:
    - wordpress-6-1.kutoku-development.com
  envVars:
  - key: PORT
    value: 80
  - key: WORDPRESS_DB_HOST
    fromService:
      name: wordpress-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: wordpress-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: wordpress-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: wordpress-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
